/**
 * generated by Xtext 2.21.0
 */
package de.sebinside.dcp.dsl.dSL.impl;

import de.sebinside.dcp.dsl.dSL.DSLPackage;
import de.sebinside.dcp.dsl.dSL.TargetModelType;
import de.sebinside.dcp.dsl.dSL.TargetModelTypeDef;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.palladiosimulator.pcm.allocation.Allocation;

import org.palladiosimulator.pcm.dataprocessing.dataprocessing.characteristics.CharacteristicTypeContainer;

import org.palladiosimulator.pcm.usagemodel.UsageModel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Target Model Type Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.sebinside.dcp.dsl.dSL.impl.TargetModelTypeDefImpl#getType <em>Type</em>}</li>
 *   <li>{@link de.sebinside.dcp.dsl.dSL.impl.TargetModelTypeDefImpl#getTypeContainer <em>Type Container</em>}</li>
 *   <li>{@link de.sebinside.dcp.dsl.dSL.impl.TargetModelTypeDefImpl#getAllocationModel <em>Allocation Model</em>}</li>
 *   <li>{@link de.sebinside.dcp.dsl.dSL.impl.TargetModelTypeDefImpl#getUsageModel <em>Usage Model</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TargetModelTypeDefImpl extends MinimalEObjectImpl.Container implements TargetModelTypeDef
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final TargetModelType TYPE_EDEFAULT = TargetModelType.OPERATION_MODEL;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected TargetModelType type = TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getTypeContainer() <em>Type Container</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeContainer()
   * @generated
   * @ordered
   */
  protected CharacteristicTypeContainer typeContainer;

  /**
   * The cached value of the '{@link #getAllocationModel() <em>Allocation Model</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAllocationModel()
   * @generated
   * @ordered
   */
  protected Allocation allocationModel;

  /**
   * The cached value of the '{@link #getUsageModel() <em>Usage Model</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsageModel()
   * @generated
   * @ordered
   */
  protected UsageModel usageModel;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TargetModelTypeDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DSLPackage.Literals.TARGET_MODEL_TYPE_DEF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TargetModelType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(TargetModelType newType)
  {
    TargetModelType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CharacteristicTypeContainer getTypeContainer()
  {
    if (typeContainer != null && ((EObject)typeContainer).eIsProxy())
    {
      InternalEObject oldTypeContainer = (InternalEObject)typeContainer;
      typeContainer = (CharacteristicTypeContainer)eResolveProxy(oldTypeContainer);
      if (typeContainer != oldTypeContainer)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE_CONTAINER, oldTypeContainer, typeContainer));
      }
    }
    return typeContainer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CharacteristicTypeContainer basicGetTypeContainer()
  {
    return typeContainer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypeContainer(CharacteristicTypeContainer newTypeContainer)
  {
    CharacteristicTypeContainer oldTypeContainer = typeContainer;
    typeContainer = newTypeContainer;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE_CONTAINER, oldTypeContainer, typeContainer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Allocation getAllocationModel()
  {
    if (allocationModel != null && ((EObject)allocationModel).eIsProxy())
    {
      InternalEObject oldAllocationModel = (InternalEObject)allocationModel;
      allocationModel = (Allocation)eResolveProxy(oldAllocationModel);
      if (allocationModel != oldAllocationModel)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DSLPackage.TARGET_MODEL_TYPE_DEF__ALLOCATION_MODEL, oldAllocationModel, allocationModel));
      }
    }
    return allocationModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Allocation basicGetAllocationModel()
  {
    return allocationModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAllocationModel(Allocation newAllocationModel)
  {
    Allocation oldAllocationModel = allocationModel;
    allocationModel = newAllocationModel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DSLPackage.TARGET_MODEL_TYPE_DEF__ALLOCATION_MODEL, oldAllocationModel, allocationModel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UsageModel getUsageModel()
  {
    if (usageModel != null && ((EObject)usageModel).eIsProxy())
    {
      InternalEObject oldUsageModel = (InternalEObject)usageModel;
      usageModel = (UsageModel)eResolveProxy(oldUsageModel);
      if (usageModel != oldUsageModel)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DSLPackage.TARGET_MODEL_TYPE_DEF__USAGE_MODEL, oldUsageModel, usageModel));
      }
    }
    return usageModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UsageModel basicGetUsageModel()
  {
    return usageModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUsageModel(UsageModel newUsageModel)
  {
    UsageModel oldUsageModel = usageModel;
    usageModel = newUsageModel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DSLPackage.TARGET_MODEL_TYPE_DEF__USAGE_MODEL, oldUsageModel, usageModel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE:
        return getType();
      case DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE_CONTAINER:
        if (resolve) return getTypeContainer();
        return basicGetTypeContainer();
      case DSLPackage.TARGET_MODEL_TYPE_DEF__ALLOCATION_MODEL:
        if (resolve) return getAllocationModel();
        return basicGetAllocationModel();
      case DSLPackage.TARGET_MODEL_TYPE_DEF__USAGE_MODEL:
        if (resolve) return getUsageModel();
        return basicGetUsageModel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE:
        setType((TargetModelType)newValue);
        return;
      case DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE_CONTAINER:
        setTypeContainer((CharacteristicTypeContainer)newValue);
        return;
      case DSLPackage.TARGET_MODEL_TYPE_DEF__ALLOCATION_MODEL:
        setAllocationModel((Allocation)newValue);
        return;
      case DSLPackage.TARGET_MODEL_TYPE_DEF__USAGE_MODEL:
        setUsageModel((UsageModel)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE_CONTAINER:
        setTypeContainer((CharacteristicTypeContainer)null);
        return;
      case DSLPackage.TARGET_MODEL_TYPE_DEF__ALLOCATION_MODEL:
        setAllocationModel((Allocation)null);
        return;
      case DSLPackage.TARGET_MODEL_TYPE_DEF__USAGE_MODEL:
        setUsageModel((UsageModel)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE:
        return type != TYPE_EDEFAULT;
      case DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE_CONTAINER:
        return typeContainer != null;
      case DSLPackage.TARGET_MODEL_TYPE_DEF__ALLOCATION_MODEL:
        return allocationModel != null;
      case DSLPackage.TARGET_MODEL_TYPE_DEF__USAGE_MODEL:
        return usageModel != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(')');
    return result.toString();
  }

} //TargetModelTypeDefImpl
