/*
 * generated by Xtext 2.20.0
 */
package de.sebinside.dcp.dsl;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;

import de.sebinside.dcp.dsl.scoping.CharacteristicsGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */

public class DSLRuntimeModule extends AbstractDSLRuntimeModule {

	public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return CharacteristicsResourceDescriptionStrategy.class;
	}

	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return CharacteristicsGlobalScopeProvider.class;
	}

}
