/**
 * generated by Xtext 2.25.0
 */
package org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.PCMDFDConstraintLanguagePackage;
import org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.PropertyClassSelector;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Property Class Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PropertyClassSelectorImpl extends de.sebinside.dcp.dsl.dSL.impl.PropertyClassSelectorImpl implements PropertyClassSelector
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PropertyClassSelectorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PCMDFDConstraintLanguagePackage.Literals.PROPERTY_CLASS_SELECTOR;
  }

} //PropertyClassSelectorImpl
