/**
 * generated by Xtext 2.20.0
 */
package de.sebinside.dcp.dsl.tests;

import com.google.inject.Inject;
import de.sebinside.dcp.dsl.dSL.Model;
import de.sebinside.dcp.dsl.tests.DSLInjectorProvider;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(DSLInjectorProvider.class)
@SuppressWarnings("all")
public class DSLParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;
  
  @Test
  public void fullTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("datatype String");
      _builder.newLine();
      _builder.append("datatype UserData");
      _builder.newLine();
      _builder.append("valueset sensitivity <- [low, high, mid]");
      _builder.newLine();
      _builder.append("attribute sensitivity <- sensitivity");
      _builder.newLine();
      _builder.append("property sensitivity <- sensitivity");
      _builder.newLine();
      _builder.newLine();
      _builder.append("class example {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sensitivity.low,");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sensitivity.high");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("constraint \"test\" {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("data.attribute.sensitivity.high NEVER FLOWS node.property.sensitivity.low");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("constraint \"test\" {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("data.class.example NEVER FLOWS node.class.!example");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("class selectorPossibilites {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sensitivity.low,");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sensitivity.!low,");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sensitivity.[low],");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sensitivity.[low, high, mid],");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sensitivity.[low & high & mid]");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
