/*
 * generated by Xtext 2.25.0
 */
package org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.PCMDFDConstraintLanguageRuntimeModule;
import org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.PCMDFDConstraintLanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PCMDFDConstraintLanguageIdeSetup extends PCMDFDConstraintLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PCMDFDConstraintLanguageRuntimeModule(), new PCMDFDConstraintLanguageIdeModule()));
	}
	
}
