/*
 * generated by Xtext 2.21.0
 */
package de.sebinside.dcp.dsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link DSLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractDSLWebModule extends DefaultWebModule {

}
