/**
 * generated by Xtext 2.20.0
 */
package de.sebinside.dcp.dsl.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getAttributeType()
 * @model
 * @generated
 */
public interface AttributeType extends CharacteristicsType
{
} // AttributeType
