/**
 * generated by Xtext 2.24.0
 */
package de.sebinside.dcp.dsl.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Characteristic Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getCharacteristicVariable()
 * @model
 * @generated
 */
public interface CharacteristicVariable extends CharacteristicVariableType
{
} // CharacteristicVariable
