/**
 * generated by Xtext 2.21.0
 */
package de.sebinside.dcp.dsl.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sebinside.dcp.dsl.dSL.Condition#getTodo <em>Todo</em>}</li>
 * </ul>
 *
 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
	 * Returns the value of the '<em><b>Todo</b></em>' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Todo</em>' reference.
	 * @see #setTodo(CharacteristicVariable)
	 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getCondition_Todo()
	 * @model
	 * @generated
	 */
  CharacteristicVariable getTodo();

  /**
	 * Sets the value of the '{@link de.sebinside.dcp.dsl.dSL.Condition#getTodo <em>Todo</em>}' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Todo</em>' reference.
	 * @see #getTodo()
	 * @generated
	 */
  void setTodo(CharacteristicVariable value);

} // Condition
