/**
 * generated by Xtext 2.21.0
 */
package de.sebinside.dcp.dsl.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sebinside.dcp.dsl.dSL.Condition#getOperation <em>Operation</em>}</li>
 * </ul>
 *
 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
	 * Returns the value of the '<em><b>Operation</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Operation</em>' containment reference.
	 * @see #setOperation(BooleanOperation)
	 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getCondition_Operation()
	 * @model containment="true"
	 * @generated
	 */
  BooleanOperation getOperation();

  /**
	 * Sets the value of the '{@link de.sebinside.dcp.dsl.dSL.Condition#getOperation <em>Operation</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Operation</em>' containment reference.
	 * @see #getOperation()
	 * @generated
	 */
  void setOperation(BooleanOperation value);

} // Condition
