/**
 * generated by Xtext 2.20.0
 */
package de.sebinside.dcp.dsl.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getDataSelector()
 * @model
 * @generated
 */
public interface DataSelector extends EObject
{
} // DataSelector
