/**
 * generated by Xtext 2.25.0
 */
package de.sebinside.dcp.dsl.dSL;

import org.palladiosimulator.dataflow.diagram.characterized.DataFlowDiagramCharacterized.CharacterizedNode;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Identitiy Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sebinside.dcp.dsl.dSL.NodeIdentitiySelector#getName <em>Name</em>}</li>
 *   <li>{@link de.sebinside.dcp.dsl.dSL.NodeIdentitiySelector#getDiaNode <em>Dia Node</em>}</li>
 * </ul>
 *
 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getNodeIdentitiySelector()
 * @model
 * @generated
 */
public interface NodeIdentitiySelector extends DestinationSelector
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getNodeIdentitiySelector_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.sebinside.dcp.dsl.dSL.NodeIdentitiySelector#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Dia Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dia Node</em>' reference.
   * @see #setDiaNode(CharacterizedNode)
   * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getNodeIdentitiySelector_DiaNode()
   * @model
   * @generated
   */
  CharacterizedNode getDiaNode();

  /**
   * Sets the value of the '{@link de.sebinside.dcp.dsl.dSL.NodeIdentitiySelector#getDiaNode <em>Dia Node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dia Node</em>' reference.
   * @see #getDiaNode()
   * @generated
   */
  void setDiaNode(CharacterizedNode value);

} // NodeIdentitiySelector
