/**
 * generated by Xtext 2.21.0
 */
package de.sebinside.dcp.dsl.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends EObject
{
} // Operation
