/**
 * generated by Xtext 2.20.0
 */
package de.sebinside.dcp.dsl.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getPropertyType()
 * @model
 * @generated
 */
public interface PropertyType extends CharacteristicsType
{
} // PropertyType
