/**
 * generated by Xtext 2.20.0
 */
package de.sebinside.dcp.dsl.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Target Model Type Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sebinside.dcp.dsl.dSL.TargetModelTypeDef#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getTargetModelTypeDef()
 * @model
 * @generated
 */
public interface TargetModelTypeDef extends EObject
{
  /**
	 * Returns the value of the '<em><b>Type</b></em>' attribute.
	 * The literals are from the enumeration {@link de.sebinside.dcp.dsl.dSL.TargetModelType}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Type</em>' attribute.
	 * @see de.sebinside.dcp.dsl.dSL.TargetModelType
	 * @see #setType(TargetModelType)
	 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getTargetModelTypeDef_Type()
	 * @model
	 * @generated
	 */
  TargetModelType getType();

  /**
	 * Sets the value of the '{@link de.sebinside.dcp.dsl.dSL.TargetModelTypeDef#getType <em>Type</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Type</em>' attribute.
	 * @see de.sebinside.dcp.dsl.dSL.TargetModelType
	 * @see #getType()
	 * @generated
	 */
  void setType(TargetModelType value);

} // TargetModelTypeDef
