/**
 * generated by Xtext 2.20.0
 */
package de.sebinside.dcp.dsl.dSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sebinside.dcp.dsl.dSL.ValueSet#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getValueSet()
 * @model
 * @generated
 */
public interface ValueSet extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Members</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' attribute list.
   * @see de.sebinside.dcp.dsl.dSL.DSLPackage#getValueSet_Members()
   * @model unique="false"
   * @generated
   */
  EList<String> getMembers();

} // ValueSet
