/*
 * generated by Xtext 2.25.0
 */
package org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PCMDFDConstraintLanguageRuntimeModule extends AbstractPCMDFDConstraintLanguageRuntimeModule {
}
