/*
 * generated by Xtext 2.25.0
 */
package org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PCMDFDConstraintLanguageUiModule extends AbstractPCMDFDConstraintLanguageUiModule {

	public PCMDFDConstraintLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
