/**
 * generated by Xtext 2.25.0
 */
package org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage;

import de.sebinside.dcp.dsl.dSL.DSLPackage;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.PCMDFDConstraintLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface PCMDFDConstraintLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pCMDFDConstraintLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.palladiosimulator.org/dataflow/confidentiality/dcp/dsl/pcm/PCMDFDConstraintLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pCMDFDConstraintLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PCMDFDConstraintLanguagePackage eINSTANCE = org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.ModelImpl
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Target Model Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TARGET_MODEL_TYPE = DSLPackage.MODEL__TARGET_MODEL_TYPE;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = DSLPackage.MODEL__ELEMENTS;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = DSLPackage.MODEL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.TargetModelTypeDefImpl <em>Target Model Type Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.TargetModelTypeDefImpl
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl#getTargetModelTypeDef()
   * @generated
   */
  int TARGET_MODEL_TYPE_DEF = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_MODEL_TYPE_DEF__TYPE = DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE;

  /**
   * The feature id for the '<em><b>Type Container</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_MODEL_TYPE_DEF__TYPE_CONTAINER = DSLPackage.TARGET_MODEL_TYPE_DEF__TYPE_CONTAINER;

  /**
   * The feature id for the '<em><b>Pcm Type Container</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_MODEL_TYPE_DEF__PCM_TYPE_CONTAINER = DSLPackage.TARGET_MODEL_TYPE_DEF_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Usage Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_MODEL_TYPE_DEF__USAGE_MODEL = DSLPackage.TARGET_MODEL_TYPE_DEF_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Repository Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_MODEL_TYPE_DEF__REPOSITORY_MODEL = DSLPackage.TARGET_MODEL_TYPE_DEF_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Target Model Type Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_MODEL_TYPE_DEF_FEATURE_COUNT = DSLPackage.TARGET_MODEL_TYPE_DEF_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PropertySelectorImpl <em>Property Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PropertySelectorImpl
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl#getPropertySelector()
   * @generated
   */
  int PROPERTY_SELECTOR = 2;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_SELECTOR__REF = DSLPackage.PROPERTY_SELECTOR__REF;

  /**
   * The number of structural features of the '<em>Property Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_SELECTOR_FEATURE_COUNT = DSLPackage.PROPERTY_SELECTOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PropertyClassSelectorImpl <em>Property Class Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PropertyClassSelectorImpl
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl#getPropertyClassSelector()
   * @generated
   */
  int PROPERTY_CLASS_SELECTOR = 3;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_CLASS_SELECTOR__REF = DSLPackage.PROPERTY_CLASS_SELECTOR__REF;

  /**
   * The number of structural features of the '<em>Property Class Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_CLASS_SELECTOR_FEATURE_COUNT = DSLPackage.PROPERTY_CLASS_SELECTOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.NodeIdentitiySelectorImpl <em>Node Identitiy Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.NodeIdentitiySelectorImpl
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl#getNodeIdentitiySelector()
   * @generated
   */
  int NODE_IDENTITIY_SELECTOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_IDENTITIY_SELECTOR__NAME = DSLPackage.NODE_IDENTITIY_SELECTOR__NAME;

  /**
   * The feature id for the '<em><b>Dia Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_IDENTITIY_SELECTOR__DIA_NODE = DSLPackage.NODE_IDENTITIY_SELECTOR__DIA_NODE;

  /**
   * The feature id for the '<em><b>Assembly</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_IDENTITIY_SELECTOR__ASSEMBLY = DSLPackage.NODE_IDENTITIY_SELECTOR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Component</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_IDENTITIY_SELECTOR__COMPONENT = DSLPackage.NODE_IDENTITIY_SELECTOR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_IDENTITIY_SELECTOR__ACTION = DSLPackage.NODE_IDENTITIY_SELECTOR_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Signature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_IDENTITIY_SELECTOR__SIGNATURE = DSLPackage.NODE_IDENTITIY_SELECTOR_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>User Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_IDENTITIY_SELECTOR__USER_ACTION = DSLPackage.NODE_IDENTITIY_SELECTOR_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Store</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_IDENTITIY_SELECTOR__STORE = DSLPackage.NODE_IDENTITIY_SELECTOR_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Node Identitiy Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_IDENTITIY_SELECTOR_FEATURE_COUNT = DSLPackage.NODE_IDENTITIY_SELECTOR_FEATURE_COUNT + 6;


  /**
   * Returns the meta object for class '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.TargetModelTypeDef <em>Target Model Type Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target Model Type Def</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.TargetModelTypeDef
   * @generated
   */
  EClass getTargetModelTypeDef();

  /**
   * Returns the meta object for the reference '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.TargetModelTypeDef#getPcmTypeContainer <em>Pcm Type Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Pcm Type Container</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.TargetModelTypeDef#getPcmTypeContainer()
   * @see #getTargetModelTypeDef()
   * @generated
   */
  EReference getTargetModelTypeDef_PcmTypeContainer();

  /**
   * Returns the meta object for the reference '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.TargetModelTypeDef#getUsageModel <em>Usage Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Usage Model</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.TargetModelTypeDef#getUsageModel()
   * @see #getTargetModelTypeDef()
   * @generated
   */
  EReference getTargetModelTypeDef_UsageModel();

  /**
   * Returns the meta object for the reference '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.TargetModelTypeDef#getRepositoryModel <em>Repository Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Repository Model</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.TargetModelTypeDef#getRepositoryModel()
   * @see #getTargetModelTypeDef()
   * @generated
   */
  EReference getTargetModelTypeDef_RepositoryModel();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.PropertySelector <em>Property Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Selector</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.PropertySelector
   * @generated
   */
  EClass getPropertySelector();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.PropertyClassSelector <em>Property Class Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Class Selector</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.PropertyClassSelector
   * @generated
   */
  EClass getPropertyClassSelector();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector <em>Node Identitiy Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Identitiy Selector</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector
   * @generated
   */
  EClass getNodeIdentitiySelector();

  /**
   * Returns the meta object for the reference '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getAssembly <em>Assembly</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Assembly</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getAssembly()
   * @see #getNodeIdentitiySelector()
   * @generated
   */
  EReference getNodeIdentitiySelector_Assembly();

  /**
   * Returns the meta object for the reference '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getComponent <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Component</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getComponent()
   * @see #getNodeIdentitiySelector()
   * @generated
   */
  EReference getNodeIdentitiySelector_Component();

  /**
   * Returns the meta object for the reference '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Action</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getAction()
   * @see #getNodeIdentitiySelector()
   * @generated
   */
  EReference getNodeIdentitiySelector_Action();

  /**
   * Returns the meta object for the reference '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getSignature <em>Signature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Signature</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getSignature()
   * @see #getNodeIdentitiySelector()
   * @generated
   */
  EReference getNodeIdentitiySelector_Signature();

  /**
   * Returns the meta object for the reference '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getUserAction <em>User Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>User Action</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getUserAction()
   * @see #getNodeIdentitiySelector()
   * @generated
   */
  EReference getNodeIdentitiySelector_UserAction();

  /**
   * Returns the meta object for the reference '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getStore <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Store</em>'.
   * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.NodeIdentitiySelector#getStore()
   * @see #getNodeIdentitiySelector()
   * @generated
   */
  EReference getNodeIdentitiySelector_Store();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PCMDFDConstraintLanguageFactory getPCMDFDConstraintLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.ModelImpl
     * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.TargetModelTypeDefImpl <em>Target Model Type Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.TargetModelTypeDefImpl
     * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl#getTargetModelTypeDef()
     * @generated
     */
    EClass TARGET_MODEL_TYPE_DEF = eINSTANCE.getTargetModelTypeDef();

    /**
     * The meta object literal for the '<em><b>Pcm Type Container</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET_MODEL_TYPE_DEF__PCM_TYPE_CONTAINER = eINSTANCE.getTargetModelTypeDef_PcmTypeContainer();

    /**
     * The meta object literal for the '<em><b>Usage Model</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET_MODEL_TYPE_DEF__USAGE_MODEL = eINSTANCE.getTargetModelTypeDef_UsageModel();

    /**
     * The meta object literal for the '<em><b>Repository Model</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET_MODEL_TYPE_DEF__REPOSITORY_MODEL = eINSTANCE.getTargetModelTypeDef_RepositoryModel();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PropertySelectorImpl <em>Property Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PropertySelectorImpl
     * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl#getPropertySelector()
     * @generated
     */
    EClass PROPERTY_SELECTOR = eINSTANCE.getPropertySelector();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PropertyClassSelectorImpl <em>Property Class Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PropertyClassSelectorImpl
     * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl#getPropertyClassSelector()
     * @generated
     */
    EClass PROPERTY_CLASS_SELECTOR = eINSTANCE.getPropertyClassSelector();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.NodeIdentitiySelectorImpl <em>Node Identitiy Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.NodeIdentitiySelectorImpl
     * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.impl.PCMDFDConstraintLanguagePackageImpl#getNodeIdentitiySelector()
     * @generated
     */
    EClass NODE_IDENTITIY_SELECTOR = eINSTANCE.getNodeIdentitiySelector();

    /**
     * The meta object literal for the '<em><b>Assembly</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_IDENTITIY_SELECTOR__ASSEMBLY = eINSTANCE.getNodeIdentitiySelector_Assembly();

    /**
     * The meta object literal for the '<em><b>Component</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_IDENTITIY_SELECTOR__COMPONENT = eINSTANCE.getNodeIdentitiySelector_Component();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_IDENTITIY_SELECTOR__ACTION = eINSTANCE.getNodeIdentitiySelector_Action();

    /**
     * The meta object literal for the '<em><b>Signature</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_IDENTITIY_SELECTOR__SIGNATURE = eINSTANCE.getNodeIdentitiySelector_Signature();

    /**
     * The meta object literal for the '<em><b>User Action</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_IDENTITIY_SELECTOR__USER_ACTION = eINSTANCE.getNodeIdentitiySelector_UserAction();

    /**
     * The meta object literal for the '<em><b>Store</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_IDENTITIY_SELECTOR__STORE = eINSTANCE.getNodeIdentitiySelector_Store();

  }

} //PCMDFDConstraintLanguagePackage
