/**
 * generated by Xtext 2.25.0
 */
package org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Class Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.palladiosimulator.dataflow.confidentiality.dcp.dsl.pcm.pCMDFDConstraintLanguage.PCMDFDConstraintLanguagePackage#getPropertyClassSelector()
 * @model
 * @generated
 */
public interface PropertyClassSelector extends de.sebinside.dcp.dsl.dSL.PropertyClassSelector
{
} // PropertyClassSelector
