/*
 * generated by Xtext 2.20.0
 */
package de.sebinside.dcp.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.sebinside.dcp.dsl.ide.contentassist.antlr.internal.InternalDSLParser;
import de.sebinside.dcp.dsl.services.DSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class DSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAbstractElementAccess().getAlternatives(), "rule__AbstractElement__Alternatives");
			builder.put(grammarAccess.getCharacteristicsTypeAccess().getAlternatives(), "rule__CharacteristicsType__Alternatives");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getAlternatives_2(), "rule__CharacteristicSelector__Alternatives_2");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getAlternatives_2_1_2(), "rule__CharacteristicSelector__Alternatives_2_1_2");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getAlternatives_2(), "rule__AltCharacteristicSelector__Alternatives_2");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getAlternatives_2_1_2(), "rule__AltCharacteristicSelector__Alternatives_2_1_2");
			builder.put(grammarAccess.getDataSelectorAccess().getAlternatives(), "rule__DataSelector__Alternatives");
			builder.put(grammarAccess.getDestinationSelectorAccess().getAlternatives(), "rule__DestinationSelector__Alternatives");
			builder.put(grammarAccess.getDataTypeAccess().getGroup(), "rule__DataType__Group__0");
			builder.put(grammarAccess.getValueSetAccess().getGroup(), "rule__ValueSet__Group__0");
			builder.put(grammarAccess.getValueSetAccess().getGroup_5(), "rule__ValueSet__Group_5__0");
			builder.put(grammarAccess.getAttributeTypeAccess().getGroup(), "rule__AttributeType__Group__0");
			builder.put(grammarAccess.getPropertyTypeAccess().getGroup(), "rule__PropertyType__Group__0");
			builder.put(grammarAccess.getCharacteristicClassAccess().getGroup(), "rule__CharacteristicClass__Group__0");
			builder.put(grammarAccess.getCharacteristicClassAccess().getGroup_4(), "rule__CharacteristicClass__Group_4__0");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getGroup(), "rule__CharacteristicSelector__Group__0");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getGroup_2_0(), "rule__CharacteristicSelector__Group_2_0__0");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getGroup_2_1(), "rule__CharacteristicSelector__Group_2_1__0");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getGroup_2_1_2_0(), "rule__CharacteristicSelector__Group_2_1_2_0__0");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getGroup_2_1_2_1(), "rule__CharacteristicSelector__Group_2_1_2_1__0");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getGroup(), "rule__AltCharacteristicSelector__Group__0");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getGroup_2_0(), "rule__AltCharacteristicSelector__Group_2_0__0");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getGroup_2_1(), "rule__AltCharacteristicSelector__Group_2_1__0");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getGroup_2_1_2_0(), "rule__AltCharacteristicSelector__Group_2_1_2_0__0");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getGroup_2_1_2_1(), "rule__AltCharacteristicSelector__Group_2_1_2_1__0");
			builder.put(grammarAccess.getImportCharacteristicsAccess().getGroup(), "rule__ImportCharacteristics__Group__0");
			builder.put(grammarAccess.getConstraintAccess().getGroup(), "rule__Constraint__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup_1(), "rule__Rule__Group_1__0");
			builder.put(grammarAccess.getRuleAccess().getGroup_4(), "rule__Rule__Group_4__0");
			builder.put(grammarAccess.getAttributeSelectorAccess().getGroup(), "rule__AttributeSelector__Group__0");
			builder.put(grammarAccess.getAttributeClassSelectorAccess().getGroup(), "rule__AttributeClassSelector__Group__0");
			builder.put(grammarAccess.getPropertySelectorAccess().getGroup(), "rule__PropertySelector__Group__0");
			builder.put(grammarAccess.getPropertyClassSelectorAccess().getGroup(), "rule__PropertyClassSelector__Group__0");
			builder.put(grammarAccess.getStatementAccess().getGroup(), "rule__Statement__Group__0");
			builder.put(grammarAccess.getModelAccess().getElementsAssignment(), "rule__Model__ElementsAssignment");
			builder.put(grammarAccess.getDataTypeAccess().getNameAssignment_1(), "rule__DataType__NameAssignment_1");
			builder.put(grammarAccess.getValueSetAccess().getNameAssignment_1(), "rule__ValueSet__NameAssignment_1");
			builder.put(grammarAccess.getValueSetAccess().getMembersAssignment_4(), "rule__ValueSet__MembersAssignment_4");
			builder.put(grammarAccess.getValueSetAccess().getMembersAssignment_5_1(), "rule__ValueSet__MembersAssignment_5_1");
			builder.put(grammarAccess.getAttributeTypeAccess().getNameAssignment_1(), "rule__AttributeType__NameAssignment_1");
			builder.put(grammarAccess.getAttributeTypeAccess().getValuesetAssignment_3(), "rule__AttributeType__ValuesetAssignment_3");
			builder.put(grammarAccess.getPropertyTypeAccess().getNameAssignment_1(), "rule__PropertyType__NameAssignment_1");
			builder.put(grammarAccess.getPropertyTypeAccess().getValuesetAssignment_3(), "rule__PropertyType__ValuesetAssignment_3");
			builder.put(grammarAccess.getCharacteristicClassAccess().getNameAssignment_1(), "rule__CharacteristicClass__NameAssignment_1");
			builder.put(grammarAccess.getCharacteristicClassAccess().getMembersAssignment_3(), "rule__CharacteristicClass__MembersAssignment_3");
			builder.put(grammarAccess.getCharacteristicClassAccess().getMembersAssignment_4_1(), "rule__CharacteristicClass__MembersAssignment_4_1");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getRefAssignment_0(), "rule__CharacteristicSelector__RefAssignment_0");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getNegatedAssignment_2_0_0(), "rule__CharacteristicSelector__NegatedAssignment_2_0_0");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getLiteralsAssignment_2_0_1(), "rule__CharacteristicSelector__LiteralsAssignment_2_0_1");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getLiteralsAssignment_2_1_1(), "rule__CharacteristicSelector__LiteralsAssignment_2_1_1");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getLiteralsAssignment_2_1_2_0_1(), "rule__CharacteristicSelector__LiteralsAssignment_2_1_2_0_1");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getConjunctedAssignment_2_1_2_1_0(), "rule__CharacteristicSelector__ConjunctedAssignment_2_1_2_1_0");
			builder.put(grammarAccess.getCharacteristicSelectorAccess().getLiteralsAssignment_2_1_2_1_1(), "rule__CharacteristicSelector__LiteralsAssignment_2_1_2_1_1");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getRefAssignment_0(), "rule__AltCharacteristicSelector__RefAssignment_0");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getNegatedAssignment_2_0_0(), "rule__AltCharacteristicSelector__NegatedAssignment_2_0_0");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getLiteralsAssignment_2_0_1(), "rule__AltCharacteristicSelector__LiteralsAssignment_2_0_1");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getLiteralsAssignment_2_1_1(), "rule__AltCharacteristicSelector__LiteralsAssignment_2_1_1");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getLiteralsAssignment_2_1_2_0_1(), "rule__AltCharacteristicSelector__LiteralsAssignment_2_1_2_0_1");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getConjunctedAssignment_2_1_2_1_0(), "rule__AltCharacteristicSelector__ConjunctedAssignment_2_1_2_1_0");
			builder.put(grammarAccess.getAltCharacteristicSelectorAccess().getLiteralsAssignment_2_1_2_1_1(), "rule__AltCharacteristicSelector__LiteralsAssignment_2_1_2_1_1");
			builder.put(grammarAccess.getImportCharacteristicsAccess().getImportURIAssignment_1(), "rule__ImportCharacteristics__ImportURIAssignment_1");
			builder.put(grammarAccess.getConstraintAccess().getNameAssignment_1(), "rule__Constraint__NameAssignment_1");
			builder.put(grammarAccess.getConstraintAccess().getRuleAssignment_3(), "rule__Constraint__RuleAssignment_3");
			builder.put(grammarAccess.getRuleAccess().getDataSelectorsAssignment_0(), "rule__Rule__DataSelectorsAssignment_0");
			builder.put(grammarAccess.getRuleAccess().getDataSelectorsAssignment_1_1(), "rule__Rule__DataSelectorsAssignment_1_1");
			builder.put(grammarAccess.getRuleAccess().getStatementAssignment_2(), "rule__Rule__StatementAssignment_2");
			builder.put(grammarAccess.getRuleAccess().getDestinationSelectorsAssignment_3(), "rule__Rule__DestinationSelectorsAssignment_3");
			builder.put(grammarAccess.getRuleAccess().getDestinationSelectorsAssignment_4_1(), "rule__Rule__DestinationSelectorsAssignment_4_1");
			builder.put(grammarAccess.getAttributeSelectorAccess().getRefAssignment_1(), "rule__AttributeSelector__RefAssignment_1");
			builder.put(grammarAccess.getAttributeClassSelectorAccess().getNegatedAssignment_1(), "rule__AttributeClassSelector__NegatedAssignment_1");
			builder.put(grammarAccess.getAttributeClassSelectorAccess().getRefAssignment_2(), "rule__AttributeClassSelector__RefAssignment_2");
			builder.put(grammarAccess.getPropertySelectorAccess().getRefAssignment_1(), "rule__PropertySelector__RefAssignment_1");
			builder.put(grammarAccess.getPropertyClassSelectorAccess().getNegatedAssignment_1(), "rule__PropertyClassSelector__NegatedAssignment_1");
			builder.put(grammarAccess.getPropertyClassSelectorAccess().getRefAssignment_2(), "rule__PropertyClassSelector__RefAssignment_2");
			builder.put(grammarAccess.getStatementAccess().getModalityAssignment_0(), "rule__Statement__ModalityAssignment_0");
			builder.put(grammarAccess.getStatementAccess().getTypeAssignment_1(), "rule__Statement__TypeAssignment_1");
			builder.put(grammarAccess.getStatementTypeAccess().getNameAssignment(), "rule__StatementType__NameAssignment");
			builder.put(grammarAccess.getStatementModalityAccess().getNameAssignment(), "rule__StatementModality__NameAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DSLGrammarAccess grammarAccess;

	@Override
	protected InternalDSLParser createParser() {
		InternalDSLParser result = new InternalDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
